version: '3'
services:
    app: &app
        build: .
        command: npm run dev
        volumes:
            - .:/app
            - node_modules:/app/node_modules/
        ports:
            - 4000:4000
            - 9000:9000
        networks:
            - main
        environment:
            NODE_ENV: development
            REACT_APP_SERVER_URL: http://localhost:4000
        tty: true
volumes:
    db_data:
    node_modules:

networks:
    main:
