version: '3'
services:
    db:
        image: postgres:9.6
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: willbenmitch
            POSTGRES_PASSWORD: P4ssword!
            POSTGRES_DB: buggerdb
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - main

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: P4ssword!
        ports:
            - 5050:80
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        links:
            - 'db:pgsql-server'
        networks:
            - main

    server: &server
        build: ./server
        command: npm run debug
        volumes:
            - ./server:/server
            - /server/node_modules/
        ports:
            - 4000:4000
            - 9000:9000
        networks:
            - main
        depends_on:
            - db
        environment:
            NODE_ENV: development
            POSTGRES_USER: willbenmitch
            POSTGRES_PASSWORD: P4ssword!
            POSTGRES_DB: buggerdb

    app: &app
        build: ./client
        command: npm run dev
        volumes:
            - ./client:/app
            - /app/node_modules/
        ports:
            - 3000:3000
        networks:
            - main
        environment:
            NODE_ENV: development
            REACT_APP_SERVER_URL: http://localhost:4000
        depends_on:
            - db
            - server
        tty: true
volumes:
    db_data:
    pgadmin_data:
    node_modules:

networks:
    main:
